#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SSH_DIR="$REPO_ROOT/.local-ssh"
PORT="${OPENCAN_LOCAL_SSH_PORT:-22222}"
started_sshd=0
integration_dotenv=""

ensure_go() {
  if command -v go >/dev/null 2>&1; then
    return
  fi
  for bin_dir in /opt/homebrew/bin /usr/local/bin; do
    if [[ -x "$bin_dir/go" ]]; then
      export PATH="$bin_dir:$PATH"
      return
    fi
  done
  echo "error: go is required for local integration run" >&2
  exit 1
}

local_arch() {
  case "$(uname -m)" in
    x86_64 | amd64) echo "amd64" ;;
    arm64 | aarch64 | arm64e) echo "arm64" ;;
    *)
      echo "error: unsupported local architecture: $(uname -m)" >&2
      exit 1
      ;;
  esac
}

find_python() {
  if command -v python3.12 >/dev/null 2>&1; then
    echo "python3.12"
    return
  fi
  if command -v python3 >/dev/null 2>&1; then
    echo "python3"
    return
  fi
  echo "error: python3.12 (preferred) or python3 is required for key formatting" >&2
  exit 1
}

cleanup() {
  if [[ -n "$integration_dotenv" && -f "$integration_dotenv" ]]; then
    rm -f "$integration_dotenv"
  fi

  if [[ "$started_sshd" -eq 1 ]] && [[ -f "$SSH_DIR/sshd.pid" ]]; then
    kill "$(cat "$SSH_DIR/sshd.pid")" 2>/dev/null || true
  fi
}
trap cleanup EXIT

"$REPO_ROOT/Scripts/setup-local-ssh.sh" >/dev/null

if [[ ! -f "$SSH_DIR/sshd.pid" ]] || ! kill -0 "$(cat "$SSH_DIR/sshd.pid")" 2>/dev/null; then
  /usr/sbin/sshd -f "$SSH_DIR/sshd_config"
  started_sshd=1
  echo "Started local sshd on 127.0.0.1:$PORT"
else
  echo "Using existing local sshd (pid $(cat "$SSH_DIR/sshd.pid"))"
fi

ensure_go
arch="$(local_arch)"
daemon_version="$(
  awk -F':=' '/^VERSION[[:space:]]*:=[[:space:]]*/ { gsub(/[[:space:]]/, "", $2); print $2; exit }' \
    "$REPO_ROOT/opencan-daemon/Makefile"
)"
if [[ -z "$daemon_version" ]]; then
  daemon_version="0.1.0"
fi

mkdir -p "$HOME/.opencan/bin"
(
  cd "$REPO_ROOT/opencan-daemon"
  GOOS=darwin GOARCH="$arch" go build \
    -ldflags="-s -w -X main.version=$daemon_version" \
    -o "$HOME/.opencan/bin/opencan-daemon" \
    ./cmd/opencan-daemon
  GOOS=darwin GOARCH="$arch" go build \
    -o "$HOME/.opencan/bin/mock-acp-server" \
    ./test/mock_acp_server
)
chmod +x "$HOME/.opencan/bin/opencan-daemon" "$HOME/.opencan/bin/mock-acp-server"
echo "Installed local daemon + mock ACP server into $HOME/.opencan/bin"

export OPENCAN_DAEMON_BUNDLE_TARGETS="linux-amd64,darwin-$arch"
export OPENCAN_TEST_AGENT_COMMAND="$HOME/.opencan/bin/mock-acp-server"
export OPENCAN_TEST_NODE_NAME="${OPENCAN_TEST_NODE_NAME:-local}"
export OPENCAN_TEST_NODE_HOST="${OPENCAN_TEST_NODE_HOST:-127.0.0.1}"
export OPENCAN_TEST_NODE_PORT="${OPENCAN_TEST_NODE_PORT:-$PORT}"
export OPENCAN_TEST_NODE_USERNAME="${OPENCAN_TEST_NODE_USERNAME:-$(whoami)}"
export OPENCAN_TEST_WORKSPACE_NAME="${OPENCAN_TEST_WORKSPACE_NAME:-home}"
export OPENCAN_TEST_WORKSPACE_PATH="${OPENCAN_TEST_WORKSPACE_PATH:-$HOME}"
export OPENCAN_TEST_SSH_KEY_PATH=""
export OPENCAN_TEST_JUMP_NODE_NAME=""
export OPENCAN_TEST_JUMP_HOST=""
export OPENCAN_TEST_JUMP_PORT=""
export OPENCAN_TEST_JUMP_USERNAME=""
export OPENCAN_TEST_JUMP_PRIVATE_KEY_PEM=""
export OPENCAN_TEST_JUMP_KEY_PATH=""
python_bin="$(find_python)"
escaped_private_key="$(
  "$python_bin" - "$SSH_DIR/test_key" <<'PY'
from pathlib import Path
import sys

raw = Path(sys.argv[1]).read_text()
raw = raw.rstrip("\n")
sys.stdout.write(raw.replace("\n", "\\n"))
PY
)"
integration_dotenv="$(mktemp "$REPO_ROOT/.env.integration.XXXXXX")"
cat > "$integration_dotenv" <<EOF
# Generated by Scripts/run-local-integration.sh for a deterministic local run.
OPENCAN_TEST_NODE_NAME=$OPENCAN_TEST_NODE_NAME
OPENCAN_TEST_NODE_HOST=$OPENCAN_TEST_NODE_HOST
OPENCAN_TEST_NODE_PORT=$OPENCAN_TEST_NODE_PORT
OPENCAN_TEST_NODE_USERNAME=$OPENCAN_TEST_NODE_USERNAME
OPENCAN_TEST_WORKSPACE_NAME=$OPENCAN_TEST_WORKSPACE_NAME
OPENCAN_TEST_WORKSPACE_PATH=$OPENCAN_TEST_WORKSPACE_PATH
OPENCAN_TEST_SSH_KEY_PATH=$OPENCAN_TEST_SSH_KEY_PATH
OPENCAN_TEST_SSH_PRIVATE_KEY_PEM="$escaped_private_key"
OPENCAN_TEST_AGENT_COMMAND=$OPENCAN_TEST_AGENT_COMMAND
OPENCAN_TEST_JUMP_NODE_NAME=
OPENCAN_TEST_JUMP_HOST=
OPENCAN_TEST_JUMP_PORT=
OPENCAN_TEST_JUMP_USERNAME=
OPENCAN_TEST_JUMP_PRIVATE_KEY_PEM=
OPENCAN_TEST_JUMP_KEY_PATH=
EOF
export OPENCAN_TEST_DOTENV_PATH="$integration_dotenv"

test_mode="${OPENCAN_INTEGRATION_TEST_MODE:-smoke}"
smoke_test_name="${OPENCAN_INTEGRATION_SMOKE_TEST:-testIntegrationSmoke}"
test_selector="-only-testing:OpenCANUIIntegrationTests/OpenCANUIIntegrationTests/$smoke_test_name"
if [[ "$test_mode" == "full" ]]; then
  test_selector=""
fi

if [[ -n "$test_selector" ]]; then
  xcodebuild test \
    -scheme OpenCAN \
    -destination "platform=iOS Simulator,name=iPhone 17 Pro" \
    "$test_selector"
else
  xcodebuild test \
    -scheme OpenCAN \
    -destination "platform=iOS Simulator,name=iPhone 17 Pro" \
    -only-testing:OpenCANUIIntegrationTests/OpenCANUIIntegrationTests
fi
